CREATE TABLE IF NOT EXISTS user (
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
occupation VARCHAR(255) NOT NULL,
phone VARCHAR(50) NOT NULL,
balance DOUBLE PRECISION NOT NULL,
birthday TIMESTAMP NOT NULL,
creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);